// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widgets/cart_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/features/cart/data/cart_repository.dart' as _i3;
import 'package:frontend/features/cart/data/models/cart_dtos.dart' as _i2;
import 'package:frontend/features/shop/domain/product.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCartDTO_0 extends _i1.SmartFake implements _i2.CartDTO {
  _FakeCartDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CartDTO> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> addToCart(
    _i5.Product? product, {
    int? quantity = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [product], {#quantity: quantity}),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(
                this,
                Invocation.method(#addToCart, [product], {#quantity: quantity}),
              ),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> updateCartItem(String? cartItemId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItem, [cartItemId, quantity]),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(
                this,
                Invocation.method(#updateCartItem, [cartItemId, quantity]),
              ),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> removeCartItem(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCartItem, [cartItemId]),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(
                this,
                Invocation.method(#removeCartItem, [cartItemId]),
              ),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> applyPromoCode(String? promoCode) =>
      (super.noSuchMethod(
            Invocation.method(#applyPromoCode, [promoCode]),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(
                this,
                Invocation.method(#applyPromoCode, [promoCode]),
              ),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> removePromoCode() =>
      (super.noSuchMethod(
            Invocation.method(#removePromoCode, []),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(this, Invocation.method(#removePromoCode, [])),
            ),
          )
          as _i4.Future<_i2.CartDTO>);

  @override
  _i4.Future<_i2.CartDTO> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<_i2.CartDTO>.value(
              _FakeCartDTO_0(this, Invocation.method(#clearCart, [])),
            ),
          )
          as _i4.Future<_i2.CartDTO>);
}
