// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/genai_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:frontend/core/genai/genai_api.dart' as _i4;
import 'package:frontend/core/network/dio_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i3.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);
}

/// A class which mocks [GenAiApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenAiApi extends _i1.Mock implements _i4.GenAiApi {
  MockGenAiApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> generateDailyMeals({
    required String? gender,
    required int? age,
    required double? heightCm,
    required double? weightKg,
    required int? stepsToday,
    required double? activeKcal24h,
    required String? target,
    List<String>? allergies,
    List<String>? preferences,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateDailyMeals, [], {
              #gender: gender,
              #age: age,
              #heightCm: heightCm,
              #weightKg: weightKg,
              #stepsToday: stepsToday,
              #activeKcal24h: activeKcal24h,
              #target: target,
              #allergies: allergies,
              #preferences: preferences,
              #userId: userId,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> generateWeeklyMeals({
    required String? gender,
    required int? age,
    required double? heightCm,
    required double? weightKg,
    required int? stepsToday,
    required double? activeKcal24h,
    required String? target,
    List<String>? allergies,
    List<String>? preferences,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateWeeklyMeals, [], {
              #gender: gender,
              #age: age,
              #heightCm: heightCm,
              #weightKg: weightKg,
              #stepsToday: stepsToday,
              #activeKcal24h: activeKcal24h,
              #target: target,
              #allergies: allergies,
              #preferences: preferences,
              #userId: userId,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
