// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/product_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/features/shop/data/models/shop_dtos.dart' as _i2;
import 'package:frontend/features/shop/data/sources/shop_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShopSearchResponse_0 extends _i1.SmartFake
    implements _i2.ShopSearchResponse {
  _FakeShopSearchResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShopProductDTO_1 extends _i1.SmartFake
    implements _i2.ShopProductDTO {
  _FakeShopProductDTO_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShopCategoryDTO_2 extends _i1.SmartFake
    implements _i2.ShopCategoryDTO {
  _FakeShopCategoryDTO_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShopVendorDTO_3 extends _i1.SmartFake implements _i2.ShopVendorDTO {
  _FakeShopVendorDTO_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ShopApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopApiService extends _i1.Mock implements _i3.ShopApiService {
  MockShopApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ShopSearchResponse> searchProducts(
    _i2.ShopSearchFilters? filters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [filters]),
            returnValue: _i4.Future<_i2.ShopSearchResponse>.value(
              _FakeShopSearchResponse_0(
                this,
                Invocation.method(#searchProducts, [filters]),
              ),
            ),
          )
          as _i4.Future<_i2.ShopSearchResponse>);

  @override
  _i4.Future<_i2.ShopProductDTO> getProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [productId]),
            returnValue: _i4.Future<_i2.ShopProductDTO>.value(
              _FakeShopProductDTO_1(
                this,
                Invocation.method(#getProduct, [productId]),
              ),
            ),
          )
          as _i4.Future<_i2.ShopProductDTO>);

  @override
  _i4.Future<List<_i2.ShopCategoryDTO>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<_i2.ShopCategoryDTO>>.value(
              <_i2.ShopCategoryDTO>[],
            ),
          )
          as _i4.Future<List<_i2.ShopCategoryDTO>>);

  @override
  _i4.Future<_i2.ShopCategoryDTO> getCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategory, [categoryId]),
            returnValue: _i4.Future<_i2.ShopCategoryDTO>.value(
              _FakeShopCategoryDTO_2(
                this,
                Invocation.method(#getCategory, [categoryId]),
              ),
            ),
          )
          as _i4.Future<_i2.ShopCategoryDTO>);

  @override
  _i4.Future<List<_i2.ShopVendorDTO>> getVendors() =>
      (super.noSuchMethod(
            Invocation.method(#getVendors, []),
            returnValue: _i4.Future<List<_i2.ShopVendorDTO>>.value(
              <_i2.ShopVendorDTO>[],
            ),
          )
          as _i4.Future<List<_i2.ShopVendorDTO>>);

  @override
  _i4.Future<_i2.ShopVendorDTO> getVendor(String? vendorId) =>
      (super.noSuchMethod(
            Invocation.method(#getVendor, [vendorId]),
            returnValue: _i4.Future<_i2.ShopVendorDTO>.value(
              _FakeShopVendorDTO_3(
                this,
                Invocation.method(#getVendor, [vendorId]),
              ),
            ),
          )
          as _i4.Future<_i2.ShopVendorDTO>);
}
